### ISSUE TITLE
Cannot read property 'options' of undefined

### ISSUE THREAD

**Issue by 0x1af2aec8f957** [timreichen/cli#3]
```ts
// file: cli.ts
import { Program } from 'program';

const program = new Program({
    name: "ts-cli",
    description: "ts-cli",
    version: "0.0.1"
});

program.parse(Deno.args);
```
### Error:
```bash
deno run --allow-all --reload --unstable --importmap=import_map.json cli.ts --help
```

```bash
error: Uncaught TypeError: Cannot read property 'options' of undefined
    const options = Object.values(this.options);
                                       ^
    at parse (command.ts:106:40)
    at parse (program.ts:52:11)
    at cli.ts:4:1
```

**Comment by timreichen** [comment]
What file is `'program'` importing? 

Tried it with `import { Program } from "https://deno.land/x/program/mod.ts"` and it worked for me.
Are you using the latest version (0.1.3)?

**Comment by 0x1af2aec8f957** [comment]
@timreichen 

> import_map.json content:

```json
"imports": {
    "program": "https://deno.land/x/program/mod.ts"
}
```

> cli.ts content:

```typescript
import { Program } from 'program';

const program = new Program({
    name: "ts-cli",
    description: "ts-cli",
    version: "0.0.1"
});

program.parse(Deno.args);
```

I can't run it here，operating environment:
```bash
deno 1.3.0
v8 8.6.334
typescript 3.9.7
```

#### Error:

```bash
deno run --allow-all --reload --unstable --importmap=import_map.json cli.ts --help
```
```bash
error: Uncaught TypeError: Cannot read property 'options' of undefined
    const options = Object.values(this.options);
                                       ^
    at parse (command.ts:106:40)
    at parse (program.ts:52:11)
    at cli.ts:4:1
```

![Error](https://user-images.githubusercontent.com/25100196/91247141-2cb54d00-e784-11ea-8dac-28a7362076a3.png)

**Comment by timreichen** [comment]
Hmm, I cannot reproduce that error with upper file setup. `this.options`  in Command is set during class initialization, so it can never be `undefined` unless manual set.
